[package]
name = "Shader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glm = "0.2.3"
rand = "0.8.5"
sdl2 = "0.35.2"
